parameters:
    database_host: 127.0.0.1
    database_port: 5432
    database_name: "task"
    database_user: "user"
    database_password: 123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt